/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.plfp;

import com.plfp.util.analyzer.BankTransactionAnalyzer;
import com.plfp.util.parser.BankStatementCSVParser;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        BankTransactionAnalyzer bankTransactionAnalyzer = new BankTransactionAnalyzer();
        bankTransactionAnalyzer.analyze("data.csv", new BankStatementCSVParser());
    }
}
